### ISSUE TITLE
相対パス指定によってfirebaseJSが取得できてない

### ISSUE THREAD

**Issue by littlebobdog** [ririringer/drawing-board#1]
https://github.com/ririringer/drawing-board/blob/f3d7d1ca5a8b9bb5a468488251eef801e7932dc1/public/service-worker.js#L1-L3

下記のように絶対パスに修正が必要。

```Diff
-importScripts("/__/firebase/9.19.0/firebase-app-compat.js");
-importScripts("/__/firebase/9.19.0/firebase-messaging-compat.js");
-importScripts("/__/firebase/init.js");
+importScripts("https://www.gstatic.com/firebasejs/9.19.0/firebase-app-compat.js");
+importScripts("https://www.gstatic.com/firebasejs/9.19.0/firebase-messaging-compat.js");
+importScripts("https://drawing-board-b1d22.firebaseapp.com/__/firebase/init.js");
```

**Comment by ririringer** [comment]
こちらもご指摘ありがとうございます！以下のように修正しています！！！
（9.19.0だとうまく動かなかったのでダウングレードしています、、、）
https://github.com/ririringer/drawing-board/blob/5f1bca1ef30a33ba90541547d4e30c92271d8724/public/firebase-messaging-sw.js#L1-L4

**Comment by ririringer** [comment]
指摘いただいたissue2つ対応することで、プッシュ通知をiOS上で受信できるようになりました！！！

**Comment by littlebobdog** [comment]
> こちらもご指摘ありがとうございます！以下のように修正しています！！！ （9.19.0だとうまく動かなかったのでダウングレードしています、、、）
> 
> https://github.com/ririringer/drawing-board/blob/5f1bca1ef30a33ba90541547d4e30c92271d8724/public/firebase-messaging-sw.js#L1-L4

LGTM
