### ISSUE TITLE
firebase.initializeAppが重複エラー

### ISSUE THREAD

**Issue by littlebobdog** [ririringer/drawing-board#2]
https://github.com/ririringer/drawing-board/blob/f3d7d1ca5a8b9bb5a468488251eef801e7932dc1/public/service-worker.js#L5-L26

https://github.com/ririringer/drawing-board/blob/f3d7d1ca5a8b9bb5a468488251eef801e7932dc1/src/config/firebase_config.js#L7

2箇所重複した定義を呼び出してることでサービスワーカーのファイルでエラーになってる。
サービスワーカーのinitializeAppは消した方が良い

**Comment by ririringer** [comment]
ありがとうございます！ちょうどそこでバグが出て開発止まってました、、、！
initializeAppを完全に消してしまうと`FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() `という別のエラーが発生したので、以下のようにinitializeされてない時だけ実行させるようにしました。

https://github.com/ririringer/drawing-board/blob/19b9af8d87c421701e2175c89c43f9e2f6caec7c/public/service-worker.js#L6

**Comment by littlebobdog** [comment]
LGTM
